/**
 * Class Seed Data - MMO-5
 *
 * 6 base classes with exact starting primary stats.
 * Class resources: Vanguard=resolve, Ranger=focus, Arcanist=mana,
 * Machinist=charge, Warden=radiance+judgement, Shade=momentum.
 * Resonances: vanguard→valor, ranger→precision, arcanist→arcana,
 * machinist→innovation, warden→sanctuary, shade→subterfuge.
 */

import { ClassDefinition } from '../models';

export const CLASSES_V1: ClassDefinition[] = [
  {
    classId: 'vanguard',
    displayName: 'Vanguard',
    description:
      'A stalwart frontline defender who protects allies and controls the battlefield through sheer resilience and powerful melee strikes.',
    primaryResource: 'resolve',
    startingStats: {
      strength: 12,
      finesse: 7,
      vitality: 12,
      intellect: 4,
      precision: 6,
      luck: 5,
      tech: 4,
      hp: 150,
      resourcePool: 100,
      armor: 20,
      attackPower: 26,
      spellPower: 9,
      movementSpeed: 5.0,
    },
    resonance: 'valor',
    roles: ['tank', 'dps'],
  },
  {
    classId: 'ranger',
    displayName: 'Ranger',
    description:
      'A precise marksman who excels at ranged combat, using keen senses and deadly accuracy to eliminate targets from a distance.',
    primaryResource: 'focus',
    startingStats: {
      strength: 6,
      finesse: 11,
      vitality: 6,
      intellect: 4,
      precision: 13,
      luck: 7,
      tech: 3,
      hp: 100,
      resourcePool: 100,
      armor: 8,
      attackPower: 14,
      spellPower: 9,
      movementSpeed: 5.5,
    },
    resonance: 'precision',
    roles: ['dps'],
  },
  {
    classId: 'arcanist',
    displayName: 'Arcanist',
    description:
      'A master of elemental magic who wields fire, frost, and storm to devastate enemies with powerful spells and arcane combinations.',
    primaryResource: 'mana',
    startingStats: {
      strength: 3,
      finesse: 6,
      vitality: 5,
      intellect: 14,
      precision: 8,
      luck: 7,
      tech: 7,
      hp: 90,
      resourcePool: 120,
      armor: 5,
      attackPower: 8,
      spellPower: 29,
      movementSpeed: 5.0,
    },
    resonance: 'arcana',
    roles: ['dps'],
  },
  {
    classId: 'machinist',
    displayName: 'Machinist',
    description:
      'A technological genius who deploys autonomous devices and drones to control the battlefield, providing support and sustained damage.',
    primaryResource: 'charge',
    startingStats: {
      strength: 4,
      finesse: 7,
      vitality: 6,
      intellect: 8,
      precision: 10,
      luck: 5,
      tech: 14,
      hp: 100,
      resourcePool: 100,
      armor: 10,
      attackPower: 10,
      spellPower: 17,
      movementSpeed: 5.0,
    },
    resonance: 'innovation',
    roles: ['dps', 'support'],
  },
  {
    classId: 'warden',
    displayName: 'Warden',
    description:
      'A divine guardian who balances offensive judgment and protective radiance, healing allies while smiting foes with holy power.',
    primaryResource: 'radiance',
    secondaryResource: 'judgement',
    startingStats: {
      strength: 5,
      finesse: 6,
      vitality: 10,
      intellect: 12,
      precision: 6,
      luck: 6,
      tech: 5,
      hp: 120,
      resourcePool: 100,
      armor: 12,
      attackPower: 12,
      spellPower: 25,
      movementSpeed: 5.0,
    },
    resonance: 'sanctuary',
    roles: ['healer', 'support'],
  },
  {
    classId: 'shade',
    displayName: 'Shade',
    description:
      'A swift assassin who strikes from the shadows, building momentum through relentless attacks to unleash devastating finishing blows.',
    primaryResource: 'momentum',
    startingStats: {
      strength: 7,
      finesse: 13,
      vitality: 5,
      intellect: 4,
      precision: 9,
      luck: 10,
      tech: 2,
      hp: 90,
      resourcePool: 5,
      armor: 6,
      attackPower: 16,
      spellPower: 9,
      movementSpeed: 6.0,
    },
    resonance: 'subterfuge',
    roles: ['dps'],
  },
];
