/**
 * Skill Seed Data - MMO-5
 *
 * 48 skills (6 classes × 8 skills each).
 * All values EXACTLY from v0.1 balance tables.
 * Percentages as decimals: 25% = 0.25, 90% = 0.90
 */

import { SkillDefinition } from '../models';

// =============================================================================
// VANGUARD (Physical Power)
// =============================================================================
const VANGUARD_SKILLS: SkillDefinition[] = [
  {
    skillId: 'vanguard_cleaving_strike',
    classId: 'vanguard',
    displayName: 'Cleaving Strike',
    description: '1.50 P + 0.60 STR, 120° arc. +8 Resolve per target; max +16.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'resolve', amount: 8, isPercentOfMax: false, perTargetBonus: 8 },
    ],
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'strength', coefficient: 0.60 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 350, recoveryMs: 300 },
    stagger: { staggerPower: 20, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.90,
      resourceOverride: { resourceId: 'resolve', amount: 12 },
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/vanguard/cleaving_strike.png',
  },
  {
    skillId: 'vanguard_shield_breaker',
    classId: 'vanguard',
    displayName: 'Shield Breaker',
    description: '1.90 P + 1.20 STR; +25% Armor Break vs guard/armor.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'attackPower', coefficient: 1.90 },
        { stat: 'strength', coefficient: 1.20 },
      ],
      element: 'physical',
      appliesStatus: 'armor_break',
    },
    timing: { castMs: 200, activeMs: 250, recoveryMs: 450 },
    stagger: {
      staggerPower: 55,
      canStagger: true,
      statusBuildup: { status: 'armor_break', value: 35 },
    },
    pvpMultipliers: {
      damageMultiplier: 0.90,
      staggerMultiplier: 0.70,
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/vanguard/shield_breaker.png',
  },
  {
    skillId: 'vanguard_brace',
    classId: 'vanguard',
    displayName: 'Brace',
    description: '60% block reduction; -30% move; +10 Resolve/block, +25 perfect. Channeled.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'resolve', amount: 10, isPercentOfMax: false },
    ],
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.60,
      scaling: [],
      conditionals: [
        { condition: 'perfect_timing', basePower: 0, scaling: [] },
      ],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 200, activePhaseType: 'hold' },
    stagger: { staggerPower: 0, staggerResist: 0.50, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { blockReduction: 0.50 },
      resourceOverride: { resourceId: 'resolve', amount: 8 },
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/vanguard/brace.png',
  },
  {
    skillId: 'vanguard_counterblow',
    classId: 'vanguard',
    displayName: 'Counterblow',
    description: '2.40 P + 1.00 STR; after perfect block 3.20 P + 1.40 STR.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'resolve', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'attackPower', coefficient: 2.40 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
      conditionals: [
        {
          condition: 'perfect_timing',
          basePower: 3.20,
          scaling: [
            { stat: 'attackPower', coefficient: 3.20 },
            { stat: 'strength', coefficient: 1.40 },
          ],
        },
      ],
    },
    timing: { castMs: 0, activeMs: 220, recoveryMs: 400 },
    stagger: {
      staggerPower: 45,
      canStagger: true,
      bonusStagger: { condition: 'perfect_timing', value: 70 },
    },
    pvpMultipliers: {
      damageMultiplier: 0.85,
      staggerMultiplier: 0.60,
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/vanguard/counterblow.png',
  },
  {
    skillId: 'vanguard_war_cry',
    classId: 'vanguard',
    displayName: 'War Cry',
    description: '8m taunt 6s; PvE threat 8×.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'taunt',
      effectDuration: 6,
    },
    timing: { castMs: 300, activeMs: 100, recoveryMs: 350 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 4,
      statusOverrides: { weaken: -0.10 },
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/vanguard/war_cry.png',
  },
  {
    skillId: 'vanguard_earthshatter',
    classId: 'vanguard',
    displayName: 'Earthshatter',
    description: '2.10 P + 1.00 STR; 5m radius. Center hit 1.5× stagger.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 35,
    resourceEffects: [
      { resourceId: 'resolve', amount: -35, isPercentOfMax: false },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 5,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
    },
    timing: { castMs: 500, activeMs: 250, recoveryMs: 650 },
    stagger: {
      staggerPower: 65,
      canStagger: true,
      bonusStagger: { condition: 'center', value: 97 },
    },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      staggerMultiplier: 0.65,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/vanguard/earthshatter.png',
  },
  {
    skillId: 'vanguard_unbreakable',
    classId: 'vanguard',
    displayName: 'Unbreakable',
    description: 'Passive: Below 30% HP: -15% dmg taken, +40% stagger resist 8s. 30s internal CD.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    internalCooldownSeconds: 30,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 8,
      conditionals: [
        {
          condition: 'below_hp_threshold',
          threshold: 0.30,
          damageMultiplier: 0.85,
        },
      ],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, staggerResist: 0.40, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 6,
      effectOverrides: { damageReduction: 0.10 },
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/vanguard/unbreakable.png',
  },
  {
    skillId: 'vanguard_overrun',
    classId: 'vanguard',
    displayName: 'Overrun',
    description: '1.30 P + 0.50 STR; travel up to 10m.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 15,
    resourceEffects: [
      { resourceId: 'resolve', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 10,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'attackPower', coefficient: 1.30 },
        { stat: 'strength', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    timing: { castMs: 100, activeMs: 600, recoveryMs: 450 },
    stagger: {
      staggerPower: 30,
      canStagger: true,
      bonusStagger: { condition: 'elite_boss', value: 65 },
    },
    pvpMultipliers: {
      damageMultiplier: 0.85,
      effectOverrides: { knockbackToFlinch: 1 },
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/vanguard/overrun.png',
  },
];

// =============================================================================
// RANGER (Physical Power; Marks last 8s)
// =============================================================================
const RANGER_SKILLS: SkillDefinition[] = [
  {
    skillId: 'ranger_quickshot',
    classId: 'ranger',
    displayName: 'Quickshot',
    description: '1.10 P + 0.50 PRE; two charges; while moving.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 5,
    charges: 2,
    chargeRechargeSeconds: 5,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 1.10,
      scaling: [
        { stat: 'attackPower', coefficient: 1.10 },
        { stat: 'precision', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 150, recoveryMs: 250 },
    stagger: { staggerPower: 8, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.90 },
    unlockLevel: 1,
    iconPath: 'icons/skills/ranger/quickshot.png',
  },
  {
    skillId: 'ranger_hunters_mark',
    classId: 'ranger',
    displayName: "Hunter's Mark",
    description: 'One Mark; reveal within 25m. Mark lasts 8s.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'mark',
      effectDuration: 8,
    },
    timing: { castMs: 150, activeMs: 50, recoveryMs: 250 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 6,
      effectOverrides: { revealRange: 15 },
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/ranger/hunters_mark.png',
  },
  {
    skillId: 'ranger_piercing_shot',
    classId: 'ranger',
    displayName: 'Piercing Shot',
    description: '2.10 P + 1.00 PRE; Mark III 3.00 P + 1.40 PRE. Consumes Marks.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 40,
    resourceEffects: [
      { resourceId: 'focus', amount: -40, isPercentOfMax: false },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.55,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'precision', coefficient: 1.00 },
      ],
      element: 'physical',
      conditionals: [
        {
          condition: 'marked',
          basePower: 3.00,
          scaling: [
            { stat: 'attackPower', coefficient: 3.00 },
            { stat: 'precision', coefficient: 1.40 },
          ],
        },
      ],
    },
    timing: { castMs: 550, activeMs: 100, recoveryMs: 600 },
    stagger: { staggerPower: 25, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      effectOverrides: { markIIICoeff: 2.70 },
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/ranger/piercing_shot.png',
  },
  {
    skillId: 'ranger_scattershot',
    classId: 'ranger',
    displayName: 'Scattershot',
    description: 'Six projectiles totaling 2.70 P + 0.90 FIN; 12m cone. Max 4 hits/target.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'focus', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 7,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 12,
    coefficients: {
      basePower: 2.70,
      scaling: [
        { stat: 'attackPower', coefficient: 2.70 },
        { stat: 'finesse', coefficient: 0.90 },
      ],
      element: 'physical',
    },
    timing: { castMs: 200, activeMs: 250, recoveryMs: 450 },
    stagger: { staggerPower: 5, staggerPerHit: 5, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.85,
      maxHitsPerTarget: 3,
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/ranger/scattershot.png',
  },
  {
    skillId: 'ranger_evade',
    classId: 'ranger',
    displayName: 'Evade',
    description: '6m dodge; 300ms i-frames; next ranged +15% crit. +10 Focus on perfect.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'focus', amount: 10, isPercentOfMax: false },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 6,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 2,
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 200 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { iFramesMs: 250, critBonus: 0.10 },
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/ranger/evade.png',
  },
  {
    skillId: 'ranger_pinning_arrow',
    classId: 'ranger',
    displayName: 'Pinning Arrow',
    description: '1.40 P + 0.70 PRE; 40% slow 4s. Mark III 1.5s root + consume.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'focus', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'attackPower', coefficient: 1.40 },
        { stat: 'precision', coefficient: 0.70 },
      ],
      element: 'physical',
      appliesStatus: 'slow',
      effectDuration: 4,
    },
    timing: { castMs: 250, activeMs: 100, recoveryMs: 400 },
    stagger: { staggerPower: 30, canStagger: true, statusBuildup: { status: 'root', value: 30 } },
    pvpMultipliers: {
      effectOverrides: { rootDuration: 1, slowPercent: 0.30, slowDuration: 3 },
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/ranger/pinning_arrow.png',
  },
  {
    skillId: 'ranger_dead_focus',
    classId: 'ranger',
    displayName: 'Dead Focus',
    description: '+20% range, +25% crit dmg, +30% weak-point. Drains 10 Focus/sec. CD after exit.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'focus', amount: -10, isPercentOfMax: false },
    ],
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'dead_focus',
    },
    timing: { castMs: 350, activeMs: 0, recoveryMs: 250, activePhaseType: 'stance' },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { rangeBonus: 0.15, critDmgBonus: 0.15, weakPointBonus: 0.20 },
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/ranger/dead_focus.png',
  },
  {
    skillId: 'ranger_predators_instinct',
    classId: 'ranger',
    displayName: "Predator's Instinct",
    description: 'Passive: Weak points +12 Focus; at 100 next offensive costs 0 and +20%. 1s gain lockout.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'focus', amount: 12, isPercentOfMax: false },
    ],
    cooldownSeconds: 0,
    internalCooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 8,
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      resourceOverride: { resourceId: 'focus', amount: 8 },
      effectOverrides: { empoweredBonus: 0.12 },
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/ranger/predators_instinct.png',
  },
];

// =============================================================================
// ARCANIST (Spell Power; Resonances 6s)
// Resource costs are % of base Mana
// =============================================================================
const ARCANIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'arcanist_ember_lance',
    classId: 'arcanist',
    displayName: 'Ember Lance',
    description: '1.70 P + 0.80 INT; applies Flame. -12% base Mana.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 12,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.12, isPercentOfMax: true },
    ],
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.35,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'spellPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      element: 'fire',
      appliesStatus: 'flame',
    },
    timing: { castMs: 350, activeMs: 100, recoveryMs: 350 },
    stagger: { staggerPower: 15, canStagger: true, statusBuildup: { status: 'burn', value: 15 } },
    pvpMultipliers: {
      damageMultiplier: 0.90,
      effectOverrides: { burnBuildup: 10 },
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/arcanist/ember_lance.png',
  },
  {
    skillId: 'arcanist_frostbind',
    classId: 'arcanist',
    displayName: 'Frostbind',
    description: '1.20 P + 0.60 INT; applies Frost; 30% slow 3s. -14% base Mana.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 14,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.14, isPercentOfMax: true },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.25,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'spellPower', coefficient: 1.20 },
        { stat: 'intellect', coefficient: 0.60 },
      ],
      element: 'ice',
      appliesStatus: 'frost',
      effectDuration: 3,
    },
    timing: { castMs: 250, activeMs: 150, recoveryMs: 400 },
    stagger: { staggerPower: 25, canStagger: true, statusBuildup: { status: 'freeze', value: 25 } },
    pvpMultipliers: {
      effectOverrides: { slowPercent: 0.20, slowDuration: 2, freezeBuildup: 15 },
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/arcanist/frostbind.png',
  },
  {
    skillId: 'arcanist_arc_surge',
    classId: 'arcanist',
    displayName: 'Arc Surge',
    description: 'Up to 4 targets 1.40 P + 0.50 INT each; Storm. -18% base Mana.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 18,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.18, isPercentOfMax: true },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.45,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'spellPower', coefficient: 1.40 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'lightning',
      appliesStatus: 'shock',
    },
    timing: { castMs: 450, activeMs: 250, recoveryMs: 450 },
    stagger: { staggerPower: 20, staggerPerHit: 20, canStagger: true, statusBuildup: { status: 'shock', value: 20 } },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      maxTargets: 3,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/arcanist/arc_surge.png',
  },
  {
    skillId: 'arcanist_aether_bolt',
    classId: 'arcanist',
    displayName: 'Aether Bolt',
    description: '1.60 P + 0.70 INT; +20% if target has Resonance. -10% base Mana.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 10,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.10, isPercentOfMax: true },
    ],
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.3,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.60,
      scaling: [
        { stat: 'spellPower', coefficient: 1.60 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'arcane',
      appliesStatus: 'aether',
    },
    timing: { castMs: 300, activeMs: 100, recoveryMs: 300 },
    stagger: { staggerPower: 10, canStagger: true },
    pvpMultipliers: {
      effectOverrides: { resonanceBonus: 0.12 },
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/arcanist/aether_bolt.png',
  },
  {
    skillId: 'arcanist_thermal_shock',
    classId: 'arcanist',
    displayName: 'Thermal Shock',
    description: 'REACTION: 2.30 P + 1.00 INT; consumes Flame+Frost. 1s/target internal CD.',
    kind: 'reaction',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    internalCooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 2.30,
      scaling: [
        { stat: 'spellPower', coefficient: 2.30 },
        { stat: 'intellect', coefficient: 1.00 },
      ],
      element: 'arcane',
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0, activePhaseType: 'reaction' },
    stagger: { staggerPower: 55, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.75,
      staggerMultiplier: 0.50,
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/arcanist/thermal_shock.png',
  },
  {
    skillId: 'arcanist_phase_step',
    classId: 'arcanist',
    displayName: 'Phase Step',
    description: 'Teleport 8m; next spell in 3s costs 30% less Mana. 200ms i-frames. -8% base Mana.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 8,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.08, isPercentOfMax: true },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 3,
    },
    timing: { castMs: 0, activeMs: 150, recoveryMs: 250 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { range: 7, noArrivalIframes: 1 },
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/arcanist/phase_step.png',
  },
  {
    skillId: 'arcanist_mana_conduit',
    classId: 'arcanist',
    displayName: 'Mana Conduit',
    description: 'Channel: Restore 30% max Mana over 2s. Interruptible.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'mana', amount: 0.30, isPercentOfMax: true },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 200, activeMs: 2000, recoveryMs: 350, activePhaseType: 'channel' },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { manaRestore: 0.20 },
      cooldownSeconds: 22,
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/arcanist/mana_conduit.png',
  },
  {
    skillId: 'arcanist_elemental_mastery',
    classId: 'arcanist',
    displayName: 'Elemental Mastery',
    description: 'Passive: Reaction +4% Spell Power 8s, max 5 stacks. 0.5s lockout.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    internalCooldownSeconds: 0.5,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.04,
      scaling: [],
      effectDuration: 8,
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { stackBonus: 0.03, maxStacks: 4 },
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/arcanist/elemental_mastery.png',
  },
];

// =============================================================================
// MACHINIST (Device Power / Tech Power)
// =============================================================================
const MACHINIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'machinist_auto_turret',
    classId: 'machinist',
    displayName: 'Auto-Turret',
    description: '15s; 15 shots at 0.45 Device Power + 0.15 PRE. -30 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 30,
    resourceEffects: [
      { resourceId: 'charge', amount: -30, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.45,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 0.45,
      scaling: [
        { stat: 'devicePower', coefficient: 0.45 },
        { stat: 'precision', coefficient: 0.15 },
      ],
      element: 'physical',
      effectDuration: 15,
    },
    timing: { castMs: 450, activeMs: 200, recoveryMs: 400 },
    stagger: { staggerPower: 3, staggerPerHit: 3, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.75,
      durationSeconds: 12,
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/machinist/auto_turret.png',
  },
  {
    skillId: 'machinist_assault_drone',
    classId: 'machinist',
    displayName: 'Assault Drone',
    description: '20s; shot every 1.25s at 0.38 Device Power + 0.12 PRE. -35 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 35,
    resourceEffects: [
      { resourceId: 'charge', amount: -35, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.38,
      scaling: [
        { stat: 'devicePower', coefficient: 0.38 },
        { stat: 'precision', coefficient: 0.12 },
      ],
      element: 'physical',
      effectDuration: 20,
    },
    timing: { castMs: 500, activeMs: 200, recoveryMs: 450 },
    stagger: { staggerPower: 3, staggerPerHit: 3, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      durationSeconds: 14,
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/machinist/assault_drone.png',
  },
  {
    skillId: 'machinist_pulse_mine',
    classId: 'machinist',
    displayName: 'Pulse Mine',
    description: '2.20 Tech Power + 0.80 TEC; arms 0.75s; max 3. -20 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'charge', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 15,
    coefficients: {
      basePower: 2.20,
      scaling: [
        { stat: 'techPower', coefficient: 2.20 },
        { stat: 'tech', coefficient: 0.80 },
      ],
      element: 'lightning',
    },
    timing: { castMs: 350, activeMs: 0, recoveryMs: 300, activePhaseType: 'deploy' },
    stagger: { staggerPower: 60, canStagger: true, statusBuildup: { status: 'shock', value: 20 } },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      staggerMultiplier: 0.50,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/machinist/pulse_mine.png',
  },
  {
    skillId: 'machinist_overclock',
    classId: 'machinist',
    displayName: 'Overclock',
    description: 'Devices +35% atk speed +20% dmg 8s then -20 durability. -20 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'charge', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'overclock',
      effectDuration: 8,
    },
    timing: { castMs: 250, activeMs: 100, recoveryMs: 350 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 6,
      effectOverrides: { atkSpeedBonus: 0.25, dmgBonus: 0.12 },
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/machinist/overclock.png',
  },
  {
    skillId: 'machinist_repair_protocol',
    classId: 'machinist',
    displayName: 'Repair Protocol',
    description: 'Player 0.60 Healing Power + 0.30 TEC; device 35% max durability. -15 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 15,
    resourceEffects: [
      { resourceId: 'charge', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 20,
    coefficients: {
      basePower: 0.60,
      scaling: [
        { stat: 'healingPower', coefficient: 0.60 },
        { stat: 'tech', coefficient: 0.30 },
      ],
    },
    timing: { castMs: 400, activeMs: 100, recoveryMs: 400 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      healingMultiplier: 0.75,
      effectOverrides: { deviceDurability: 0.25 },
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/machinist/repair_protocol.png',
  },
  {
    skillId: 'machinist_shock_net',
    classId: 'machinist',
    displayName: 'Shock Net',
    description: '5m field 5s; 35% slow; 12 Shock/sec. Stun at threshold. -25 Charge.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'charge', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'shock',
      effectDuration: 5,
    },
    timing: { castMs: 400, activeMs: 0, recoveryMs: 400, activePhaseType: 'deploy' },
    stagger: { staggerPower: 12, staggerPerHit: 12, canStagger: true, statusBuildup: { status: 'shock', value: 12 } },
    pvpMultipliers: {
      durationSeconds: 4,
      effectOverrides: { slowPercent: 0.25 },
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/machinist/shock_net.png',
  },
  {
    skillId: 'machinist_salvage',
    classId: 'machinist',
    displayName: 'Salvage',
    description: 'Passive: Natural expiry refunds 25%; manual 40%.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'charge', amount: 25, isPercentOfMax: false },
    ],
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { manualRefund: 0.30 },
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/machinist/salvage.png',
  },
  {
    skillId: 'machinist_remote_detonation',
    classId: 'machinist',
    displayName: 'Remote Detonation',
    description: 'Turret 1.10, drone 1.40, mine 2.40 Device Power. Stagger: 25/35/65.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 1.10,
      scaling: [{ stat: 'devicePower', coefficient: 1.10 }],
      element: 'fire',
      targetVariants: {
        turret: { basePower: 1.10, scaling: [{ stat: 'devicePower', coefficient: 1.10 }] },
        drone: { basePower: 1.40, scaling: [{ stat: 'devicePower', coefficient: 1.40 }] },
        mine: { basePower: 2.40, scaling: [{ stat: 'devicePower', coefficient: 2.40 }] },
      },
    },
    timing: { castMs: 150, activeMs: 100, recoveryMs: 500 },
    stagger: {
      staggerPower: 25,
      canStagger: true,
      targetVariants: { turret: 25, drone: 35, mine: 65 },
    },
    pvpMultipliers: {
      damageMultiplier: 0.70,
      maxTargets: 2,
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/machinist/remote_detonation.png',
  },
];

// =============================================================================
// WARDEN (Spell Power / Healing Power)
// =============================================================================
const WARDEN_SKILLS: SkillDefinition[] = [
  {
    skillId: 'warden_radiant_strike',
    classId: 'warden',
    displayName: 'Radiant Strike',
    description: '1.30 Spell Power + 0.50 INT. +15 Radiance.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'radiance', amount: 15, isPercentOfMax: false },
    ],
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'spellPower', coefficient: 1.30 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'radiant',
    },
    timing: { castMs: 150, activeMs: 250, recoveryMs: 350 },
    stagger: { staggerPower: 15, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.90,
      resourceOverride: { resourceId: 'radiance', amount: 12 },
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/warden/radiant_strike.png',
  },
  {
    skillId: 'warden_mend',
    classId: 'warden',
    displayName: 'Mend',
    description: '1.70 Healing Power + 0.50 INT. +15 Judgement.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'judgement', amount: 15, isPercentOfMax: false },
    ],
    cooldownSeconds: 3,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.45,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'healingPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
    },
    timing: { castMs: 450, activeMs: 100, recoveryMs: 400 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      healingMultiplier: 0.80,
      resourceOverride: { resourceId: 'judgement', amount: 12 },
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/warden/mend.png',
  },
  {
    skillId: 'warden_sanctuary',
    classId: 'warden',
    displayName: 'Sanctuary',
    description: '8s field; eight ticks totaling 2.40 Healing Power + 0.80 INT. -30 Radiance.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 30,
    resourceEffects: [
      { resourceId: 'radiance', amount: -30, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.6,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'healingPower', coefficient: 2.40 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      appliesStatus: 'sanctuary',
      effectDuration: 8,
    },
    timing: { castMs: 600, activeMs: 0, recoveryMs: 500, activePhaseType: 'deploy' },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      healingMultiplier: 0.70,
      durationSeconds: 6,
      effectOverrides: { noEnemyDebuff: 1 },
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/warden/sanctuary.png',
  },
  {
    skillId: 'warden_condemn',
    classId: 'warden',
    displayName: 'Condemn',
    description: '1.90 Spell Power + 0.70 INT; target -10% dmg 5s. -25 Judgement.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'judgement', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.35,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'spellPower', coefficient: 1.90 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'radiant',
      appliesStatus: 'weaken',
      effectDuration: 5,
    },
    timing: { castMs: 350, activeMs: 150, recoveryMs: 450 },
    stagger: { staggerPower: 20, canStagger: true, statusBuildup: { status: 'weaken', value: 20 } },
    pvpMultipliers: {
      damageMultiplier: 0.85,
      effectOverrides: { weakenPercent: 0.08, weakenDuration: 3 },
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/warden/condemn.png',
  },
  {
    skillId: 'warden_guardian_light',
    classId: 'warden',
    displayName: 'Guardian Light',
    description: '10% target Max HP + 0.70 Healing Power; 8s. -25 Radiance; -15 Judgement.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'radiance', amount: -25, isPercentOfMax: false },
      { resourceId: 'judgement', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.10,
      scaling: [
        { stat: 'maxHp', coefficient: 0.10 },
        { stat: 'healingPower', coefficient: 0.70 },
      ],
      appliesStatus: 'guardian_light',
      effectDuration: 8,
    },
    timing: { castMs: 300, activeMs: 100, recoveryMs: 350 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { maxHpPercent: 0.07 },
      durationSeconds: 6,
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/warden/guardian_light.png',
  },
  {
    skillId: 'warden_equilibrium',
    classId: 'warden',
    displayName: 'Equilibrium',
    description: '+20% dmg/heal 10s; cross-effects 15% of triggering result. -50 Radiance; -50 Judgement.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 50,
    resourceEffects: [
      { resourceId: 'radiance', amount: -50, isPercentOfMax: false },
      { resourceId: 'judgement', amount: -50, isPercentOfMax: false },
    ],
    cooldownSeconds: 45,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'equilibrium',
      effectDuration: 10,
    },
    timing: { castMs: 500, activeMs: 100, recoveryMs: 400 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 8,
      effectOverrides: { dmgHealBonus: 0.12, crossEffectPercent: 0.10 },
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/warden/equilibrium.png',
  },
  {
    skillId: 'warden_divine_intervention',
    classId: 'warden',
    displayName: 'Divine Intervention',
    description: 'Cannot fall below 1 HP for 2s, then 2.50 Healing Power + 1.00 INT. Exhausted 90s. -40 Judgement.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 40,
    resourceEffects: [
      { resourceId: 'judgement', amount: -40, isPercentOfMax: false },
    ],
    cooldownSeconds: 120,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 2.50,
      scaling: [
        { stat: 'healingPower', coefficient: 2.50 },
        { stat: 'intellect', coefficient: 1.00 },
      ],
      appliesStatus: 'divine_intervention',
    },
    antiDeathDurationSeconds: 2,
    exhaustedDurationSeconds: 90,
    timing: { castMs: 250, activeMs: 100, recoveryMs: 350 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      healingMultiplier: 0.70,
      durationSeconds: 1,
      exhaustedDurationSeconds: 120,
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/warden/divine_intervention.png',
  },
  {
    skillId: 'warden_balance_within',
    classId: 'warden',
    displayName: 'Balance Within',
    description: 'Passive: Harmony +2% dmg/heal per stack, max 5. Same-type resets.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.02,
      scaling: [],
      appliesStatus: 'harmony',
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { stackBonus: 0.015, maxStacks: 4 },
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/warden/balance_within.png',
  },
];

// =============================================================================
// SHADE (Physical Power; finishers spend all Momentum)
// =============================================================================
const SHADE_SKILLS: SkillDefinition[] = [
  {
    skillId: 'shade_razor_cut',
    classId: 'shade',
    displayName: 'Razor Cut',
    description: '1.20 P + 0.50 FIN; +30% from behind. +1 Momentum.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'momentum', amount: 1, isPercentOfMax: false },
    ],
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'attackPower', coefficient: 1.20 },
        { stat: 'finesse', coefficient: 0.50 },
      ],
      element: 'physical',
      conditionals: [
        { condition: 'flanking', damageMultiplier: 1.30 },
      ],
    },
    timing: { castMs: 0, activeMs: 220, recoveryMs: 280 },
    stagger: { staggerPower: 8, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.90,
      effectOverrides: { rearBonus: 0.20 },
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/shade/razor_cut.png',
  },
  {
    skillId: 'shade_shadowstep',
    classId: 'shade',
    displayName: 'Shadowstep',
    description: 'Teleport behind within 10m; next atk +20% crit 3s.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 10,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 3,
    },
    timing: { castMs: 0, activeMs: 150, recoveryMs: 250 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { range: 8, critBonus: 0.15 },
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/shade/shadowstep.png',
  },
  {
    skillId: 'shade_venom_edge',
    classId: 'shade',
    displayName: 'Venom Edge',
    description: '10s weapon buff; 5th stack 1.80 P + 0.80 LCK over 6s. -1 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    resourceEffects: [
      { resourceId: 'momentum', amount: -1, isPercentOfMax: false },
    ],
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.80,
      scaling: [
        { stat: 'attackPower', coefficient: 1.80 },
        { stat: 'luck', coefficient: 0.80 },
      ],
      element: 'nature',
      appliesStatus: 'venom',
      effectDuration: 10,
    },
    timing: { castMs: 200, activeMs: 0, recoveryMs: 300, activePhaseType: 'buff' },
    stagger: { staggerPower: 15, staggerPerHit: 15, canStagger: true, statusBuildup: { status: 'poison', value: 15 } },
    pvpMultipliers: {
      damageMultiplier: 0.75,
      durationSeconds: 4,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/shade/venom_edge.png',
  },
  {
    skillId: 'shade_smoke_veil',
    classId: 'shade',
    displayName: 'Smoke Veil',
    description: '5m field 6s; +20% glance inside. -2 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    resourceEffects: [
      { resourceId: 'momentum', amount: -2, isPercentOfMax: false },
    ],
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 5,
    coefficients: {
      basePower: 0,
      scaling: [],
      effectDuration: 6,
    },
    timing: { castMs: 250, activeMs: 0, recoveryMs: 350, activePhaseType: 'deploy' },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 4,
      effectOverrides: { glanceBonus: 0.12, noLockOnBreak: 8 },
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/shade/smoke_veil.png',
  },
  {
    skillId: 'shade_sever',
    classId: 'shade',
    displayName: 'Sever',
    description: '1.50/2.00/2.60/3.30/4.20 P + 0.40 FIN per stack. Spend all Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    resourceEffects: [
      { resourceId: 'momentum', amount: -5, isPercentOfMax: false },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'finesse', coefficient: 0.40 },
      ],
      element: 'physical',
      perStack: {
        basePowerPerStack: [1.50, 2.00, 2.60, 3.30, 4.20],
        scalingPerStack: [
          [{ stat: 'attackPower', coefficient: 1.50 }, { stat: 'finesse', coefficient: 0.40 }],
          [{ stat: 'attackPower', coefficient: 2.00 }, { stat: 'finesse', coefficient: 0.80 }],
          [{ stat: 'attackPower', coefficient: 2.60 }, { stat: 'finesse', coefficient: 1.20 }],
          [{ stat: 'attackPower', coefficient: 3.30 }, { stat: 'finesse', coefficient: 1.60 }],
          [{ stat: 'attackPower', coefficient: 4.20 }, { stat: 'finesse', coefficient: 2.00 }],
        ],
      },
    },
    timing: { castMs: 250, activeMs: 200, recoveryMs: 550 },
    stagger: { staggerPower: 15, perStackStagger: 15, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.80,
      effectOverrides: { fiveStackCoeff: 3.60 },
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/shade/sever.png',
  },
  {
    skillId: 'shade_execution',
    classId: 'shade',
    displayName: 'Execution',
    description: 'Below 25% HP: 2.00 P + 2.00 P × MissingHealthPercent; bosses cap 3.25 P. -3 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 3,
    resourceEffects: [
      { resourceId: 'momentum', amount: -3, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.00,
      scaling: [
        { stat: 'attackPower', coefficient: 2.00 },
        { stat: 'missingHpPercent', coefficient: 2.00 },
      ],
      element: 'shadow',
      conditionals: [
        {
          condition: 'below_hp_threshold',
          threshold: 0.25,
        },
        {
          condition: 'boss_target',
          basePower: 3.25,
          scaling: [{ stat: 'attackPower', coefficient: 3.25 }],
        },
      ],
    },
    timing: { castMs: 400, activeMs: 150, recoveryMs: 600 },
    stagger: { staggerPower: 30, canStagger: true },
    pvpMultipliers: {
      damageMultiplier: 0.75,
      missingHealthCap: 1.00,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/shade/execution.png',
  },
  {
    skillId: 'shade_phantom_double',
    classId: 'shade',
    displayName: 'Phantom Double',
    description: '8s duplicate; 30% basic attacks; 15% owner Max HP. -2 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    resourceEffects: [
      { resourceId: 'momentum', amount: -2, isPercentOfMax: false },
    ],
    cooldownSeconds: 24,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0.30,
      scaling: [{ stat: 'attackPower', coefficient: 0.30 }],
      element: 'shadow',
      effectDuration: 8,
    },
    timing: { castMs: 350, activeMs: 0, recoveryMs: 400, activePhaseType: 'summon' },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      durationSeconds: 6,
      effectOverrides: { effectiveness: 0.20, noBodyBlock: 1 },
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/shade/phantom_double.png',
  },
  {
    skillId: 'shade_relentless',
    classId: 'shade',
    displayName: 'Relentless',
    description: 'Passive: Crits 20% chance Momentum; perfect dodge guarantees one. 1s crit lockout.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'momentum', amount: 1, isPercentOfMax: false },
    ],
    cooldownSeconds: 0,
    internalCooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: {
      effectOverrides: { critProcChance: 0.15 },
      cooldownSeconds: 1.5,
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/shade/relentless.png',
  },
];

export const SKILLS_V1: SkillDefinition[] = [
  ...VANGUARD_SKILLS,
  ...RANGER_SKILLS,
  ...ARCANIST_SKILLS,
  ...MACHINIST_SKILLS,
  ...WARDEN_SKILLS,
  ...SHADE_SKILLS,
];

/**
 * Expected timing/stagger/pvp values for test assertions.
 * Format: skillId -> { timing, stagger, pvpDamage }
 */
export const SKILL_SPEC_VALUES: Record<string, {
  timing: { castMs: number; activeMs: number; recoveryMs: number };
  stagger: number;
  pvpDamage?: number;
}> = {
  // Vanguard
  vanguard_cleaving_strike: { timing: { castMs: 0, activeMs: 350, recoveryMs: 300 }, stagger: 20, pvpDamage: 0.90 },
  vanguard_shield_breaker: { timing: { castMs: 200, activeMs: 250, recoveryMs: 450 }, stagger: 55, pvpDamage: 0.90 },
  vanguard_brace: { timing: { castMs: 0, activeMs: 0, recoveryMs: 200 }, stagger: 0 },
  vanguard_counterblow: { timing: { castMs: 0, activeMs: 220, recoveryMs: 400 }, stagger: 45, pvpDamage: 0.85 },
  vanguard_war_cry: { timing: { castMs: 300, activeMs: 100, recoveryMs: 350 }, stagger: 0 },
  vanguard_earthshatter: { timing: { castMs: 500, activeMs: 250, recoveryMs: 650 }, stagger: 65, pvpDamage: 0.80 },
  vanguard_unbreakable: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
  vanguard_overrun: { timing: { castMs: 100, activeMs: 600, recoveryMs: 450 }, stagger: 30, pvpDamage: 0.85 },
  // Ranger
  ranger_quickshot: { timing: { castMs: 0, activeMs: 150, recoveryMs: 250 }, stagger: 8, pvpDamage: 0.90 },
  ranger_hunters_mark: { timing: { castMs: 150, activeMs: 50, recoveryMs: 250 }, stagger: 0 },
  ranger_piercing_shot: { timing: { castMs: 550, activeMs: 100, recoveryMs: 600 }, stagger: 25, pvpDamage: 0.80 },
  ranger_scattershot: { timing: { castMs: 200, activeMs: 250, recoveryMs: 450 }, stagger: 5, pvpDamage: 0.85 },
  ranger_evade: { timing: { castMs: 0, activeMs: 300, recoveryMs: 200 }, stagger: 0 },
  ranger_pinning_arrow: { timing: { castMs: 250, activeMs: 100, recoveryMs: 400 }, stagger: 30 },
  ranger_dead_focus: { timing: { castMs: 350, activeMs: 0, recoveryMs: 250 }, stagger: 0 },
  ranger_predators_instinct: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
  // Arcanist
  arcanist_ember_lance: { timing: { castMs: 350, activeMs: 100, recoveryMs: 350 }, stagger: 15, pvpDamage: 0.90 },
  arcanist_frostbind: { timing: { castMs: 250, activeMs: 150, recoveryMs: 400 }, stagger: 25 },
  arcanist_arc_surge: { timing: { castMs: 450, activeMs: 250, recoveryMs: 450 }, stagger: 20, pvpDamage: 0.80 },
  arcanist_aether_bolt: { timing: { castMs: 300, activeMs: 100, recoveryMs: 300 }, stagger: 10 },
  arcanist_thermal_shock: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 55, pvpDamage: 0.75 },
  arcanist_phase_step: { timing: { castMs: 0, activeMs: 150, recoveryMs: 250 }, stagger: 0 },
  arcanist_mana_conduit: { timing: { castMs: 200, activeMs: 2000, recoveryMs: 350 }, stagger: 0 },
  arcanist_elemental_mastery: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
  // Machinist
  machinist_auto_turret: { timing: { castMs: 450, activeMs: 200, recoveryMs: 400 }, stagger: 3, pvpDamage: 0.75 },
  machinist_assault_drone: { timing: { castMs: 500, activeMs: 200, recoveryMs: 450 }, stagger: 3, pvpDamage: 0.80 },
  machinist_pulse_mine: { timing: { castMs: 350, activeMs: 0, recoveryMs: 300 }, stagger: 60, pvpDamage: 0.80 },
  machinist_overclock: { timing: { castMs: 250, activeMs: 100, recoveryMs: 350 }, stagger: 0 },
  machinist_repair_protocol: { timing: { castMs: 400, activeMs: 100, recoveryMs: 400 }, stagger: 0 },
  machinist_shock_net: { timing: { castMs: 400, activeMs: 0, recoveryMs: 400 }, stagger: 12 },
  machinist_salvage: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
  machinist_remote_detonation: { timing: { castMs: 150, activeMs: 100, recoveryMs: 500 }, stagger: 25, pvpDamage: 0.70 },
  // Warden
  warden_radiant_strike: { timing: { castMs: 150, activeMs: 250, recoveryMs: 350 }, stagger: 15, pvpDamage: 0.90 },
  warden_mend: { timing: { castMs: 450, activeMs: 100, recoveryMs: 400 }, stagger: 0 },
  warden_sanctuary: { timing: { castMs: 600, activeMs: 0, recoveryMs: 500 }, stagger: 0 },
  warden_condemn: { timing: { castMs: 350, activeMs: 150, recoveryMs: 450 }, stagger: 20, pvpDamage: 0.85 },
  warden_guardian_light: { timing: { castMs: 300, activeMs: 100, recoveryMs: 350 }, stagger: 0 },
  warden_equilibrium: { timing: { castMs: 500, activeMs: 100, recoveryMs: 400 }, stagger: 0 },
  warden_divine_intervention: { timing: { castMs: 250, activeMs: 100, recoveryMs: 350 }, stagger: 0 },
  warden_balance_within: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
  // Shade
  shade_razor_cut: { timing: { castMs: 0, activeMs: 220, recoveryMs: 280 }, stagger: 8, pvpDamage: 0.90 },
  shade_shadowstep: { timing: { castMs: 0, activeMs: 150, recoveryMs: 250 }, stagger: 0 },
  shade_venom_edge: { timing: { castMs: 200, activeMs: 0, recoveryMs: 300 }, stagger: 15, pvpDamage: 0.75 },
  shade_smoke_veil: { timing: { castMs: 250, activeMs: 0, recoveryMs: 350 }, stagger: 0 },
  shade_sever: { timing: { castMs: 250, activeMs: 200, recoveryMs: 550 }, stagger: 15, pvpDamage: 0.80 },
  shade_execution: { timing: { castMs: 400, activeMs: 150, recoveryMs: 600 }, stagger: 30, pvpDamage: 0.75 },
  shade_phantom_double: { timing: { castMs: 350, activeMs: 0, recoveryMs: 400 }, stagger: 0 },
  shade_relentless: { timing: { castMs: 0, activeMs: 0, recoveryMs: 0 }, stagger: 0 },
};
