/**
 * Skill Seed Data - MMO-5
 *
 * 48 skills (6 classes × 8 skills each).
 * All coefficients as decimals: 150% → 1.50, 15% → 0.15
 * NOTE: Thermal Shock MUST be kind='reaction' (not active)
 */

import { SkillDefinition } from '../models';

// =============================================================================
// Vanguard Skills (Physical Power scaling)
// =============================================================================
const VANGUARD_SKILLS: SkillDefinition[] = [
  {
    skillId: 'vanguard_cleaving_strike',
    classId: 'vanguard',
    displayName: 'Cleaving Strike',
    description:
      'A wide sweeping attack that cleaves through enemies, generating Resolve for each target hit.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'strength', coefficient: 0.60 },
      ],
      element: 'physical',
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/vanguard/cleaving_strike.png',
  },
  {
    skillId: 'vanguard_shield_breaker',
    classId: 'vanguard',
    displayName: 'Shield Breaker',
    description:
      'A devastating blow that sunders enemy defenses, applying armor break.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'attackPower', coefficient: 1.90 },
        { stat: 'strength', coefficient: 1.20 },
      ],
      element: 'physical',
      appliesStatus: 'armor_break',
      effectDuration: 6,
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/vanguard/shield_breaker.png',
  },
  {
    skillId: 'vanguard_brace',
    classId: 'vanguard',
    displayName: 'Brace',
    description:
      'Channel to significantly reduce incoming damage while braced, but movement is slowed.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.60,
      scaling: [],
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/vanguard/brace.png',
  },
  {
    skillId: 'vanguard_counterblow',
    classId: 'vanguard',
    displayName: 'Counterblow',
    description:
      'Counter an incoming attack. Perfect timing greatly increases damage dealt.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 20,
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'attackPower', coefficient: 2.40 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/vanguard/counterblow.png',
  },
  {
    skillId: 'vanguard_war_cry',
    classId: 'vanguard',
    displayName: 'War Cry',
    description:
      'Let out a fearsome war cry that taunts all enemies within 8 meters for 6 seconds.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'taunt',
      effectDuration: 6,
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/vanguard/war_cry.png',
  },
  {
    skillId: 'vanguard_earthshatter',
    classId: 'vanguard',
    displayName: 'Earthshatter',
    description:
      'Slam the ground with tremendous force, dealing damage and staggering enemies.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 35,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
      appliesStatus: 'stagger',
      effectDuration: 2,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/vanguard/earthshatter.png',
  },
  {
    skillId: 'vanguard_unbreakable',
    classId: 'vanguard',
    displayName: 'Unbreakable',
    description:
      'When falling below 30% HP, gain damage reduction and stagger resistance for 8 seconds. Internal cooldown: 30s.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 30,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.15,
      scaling: [],
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/vanguard/unbreakable.png',
  },
  {
    skillId: 'vanguard_overrun',
    classId: 'vanguard',
    displayName: 'Overrun',
    description: 'Charge forward, knocking aside enemies in your path.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 15,
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 12,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'attackPower', coefficient: 1.30 },
        { stat: 'strength', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/vanguard/overrun.png',
  },
];

// =============================================================================
// Ranger Skills (Physical Power scaling)
// =============================================================================
const RANGER_SKILLS: SkillDefinition[] = [
  {
    skillId: 'ranger_quickshot',
    classId: 'ranger',
    displayName: 'Quickshot',
    description:
      'Fire a quick shot while moving. Has 2 charges that recharge independently.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 5,
    charges: 2,
    chargeRechargeSeconds: 5,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 1.10,
      scaling: [
        { stat: 'attackPower', coefficient: 1.10 },
        { stat: 'precision', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/ranger/quickshot.png',
  },
  {
    skillId: 'ranger_hunters_mark',
    classId: 'ranger',
    displayName: "Hunter's Mark",
    description:
      'Mark a target, increasing damage taken and enabling Mark-empowered abilities.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'mark',
      effectDuration: 12,
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/ranger/hunters_mark.png',
  },
  {
    skillId: 'ranger_piercing_shot',
    classId: 'ranger',
    displayName: 'Piercing Shot',
    description:
      'Fire a powerful shot that pierces through enemies. Deals increased damage to Marked targets.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 40,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'precision', coefficient: 1.00 },
      ],
      element: 'physical',
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/ranger/piercing_shot.png',
  },
  {
    skillId: 'ranger_scattershot',
    classId: 'ranger',
    displayName: 'Scattershot',
    description:
      'Fire a spread of projectiles that hit multiple targets in a cone.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 25,
    cooldownSeconds: 7,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 15,
    coefficients: {
      basePower: 2.70,
      scaling: [
        { stat: 'attackPower', coefficient: 2.70 },
        { stat: 'finesse', coefficient: 0.90 },
      ],
      element: 'physical',
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/ranger/scattershot.png',
  },
  {
    skillId: 'ranger_evade',
    classId: 'ranger',
    displayName: 'Evade',
    description: 'Quickly dodge in the direction of movement, avoiding attacks.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/ranger/evade.png',
  },
  {
    skillId: 'ranger_pinning_arrow',
    classId: 'ranger',
    displayName: 'Pinning Arrow',
    description: 'Fire an arrow that pins the target in place, immobilizing them.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 20,
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'attackPower', coefficient: 1.40 },
        { stat: 'precision', coefficient: 0.70 },
      ],
      element: 'physical',
      appliesStatus: 'immobilize',
      effectDuration: 3,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/ranger/pinning_arrow.png',
  },
  {
    skillId: 'ranger_dead_focus',
    classId: 'ranger',
    displayName: 'Dead Focus',
    description:
      'Enter a focused stance that drains Focus but greatly increases damage and accuracy.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 0,
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'dead_focus',
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/ranger/dead_focus.png',
  },
  {
    skillId: 'ranger_predators_instinct',
    classId: 'ranger',
    displayName: "Predator's Instinct",
    description:
      'Passively increases critical hit chance against Marked targets and reveals stealthed enemies.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/ranger/predators_instinct.png',
  },
];

// =============================================================================
// Arcanist Skills (Spell Power scaling)
// NOTE: Thermal Shock is kind='reaction' (NOT active)
// =============================================================================
const ARCANIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'arcanist_ember_lance',
    classId: 'arcanist',
    displayName: 'Ember Lance',
    description:
      'Launch a searing lance of flame that burns the target, applying Flame status.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 15,
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'spellPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      element: 'fire',
      appliesStatus: 'flame',
      effectDuration: 6,
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/arcanist/ember_lance.png',
  },
  {
    skillId: 'arcanist_frostbind',
    classId: 'arcanist',
    displayName: 'Frostbind',
    description:
      'Conjure icy chains that damage and slow the target, applying Frost status.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 20,
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'spellPower', coefficient: 1.20 },
        { stat: 'intellect', coefficient: 0.60 },
      ],
      element: 'ice',
      appliesStatus: 'frost',
      effectDuration: 4,
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/arcanist/frostbind.png',
  },
  {
    skillId: 'arcanist_arc_surge',
    classId: 'arcanist',
    displayName: 'Arc Surge',
    description:
      'Release a surge of lightning that chains to up to 4 nearby enemies.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 30,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'spellPower', coefficient: 1.40 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'lightning',
      appliesStatus: 'shock',
      effectDuration: 3,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/arcanist/arc_surge.png',
  },
  {
    skillId: 'arcanist_aether_bolt',
    classId: 'arcanist',
    displayName: 'Aether Bolt',
    description: 'Fire a bolt of pure arcane energy with a short cooldown.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 10,
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.3,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.60,
      scaling: [
        { stat: 'spellPower', coefficient: 1.60 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'arcane',
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/arcanist/aether_bolt.png',
  },
  {
    skillId: 'arcanist_thermal_shock',
    classId: 'arcanist',
    displayName: 'Thermal Shock',
    description:
      'REACTION: Consumes both Flame and Frost on a target to trigger a devastating thermal reaction. 1s internal cooldown per target.',
    kind: 'reaction',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 2.30,
      scaling: [
        { stat: 'spellPower', coefficient: 2.30 },
        { stat: 'intellect', coefficient: 1.00 },
      ],
      element: 'arcane',
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/arcanist/thermal_shock.png',
  },
  {
    skillId: 'arcanist_phase_step',
    classId: 'arcanist',
    displayName: 'Phase Step',
    description: 'Teleport a short distance in the target direction.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 25,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 15,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/arcanist/phase_step.png',
  },
  {
    skillId: 'arcanist_mana_conduit',
    classId: 'arcanist',
    displayName: 'Mana Conduit',
    description:
      'Channel to rapidly restore mana. Cannot move or use other abilities while channeling.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 3,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/arcanist/mana_conduit.png',
  },
  {
    skillId: 'arcanist_elemental_mastery',
    classId: 'arcanist',
    displayName: 'Elemental Mastery',
    description:
      'Passive: Increases all elemental damage dealt and reduces elemental damage taken.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.15,
      scaling: [],
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/arcanist/elemental_mastery.png',
  },
];

// =============================================================================
// Machinist Skills (Tech/Device Power scaling)
// =============================================================================
const MACHINIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'machinist_auto_turret',
    classId: 'machinist',
    displayName: 'Auto-Turret',
    description:
      'Deploy an autonomous turret that attacks nearby enemies with sustained fire.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 30,
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 0.45,
      scaling: [
        { stat: 'techPower', coefficient: 0.45 },
        { stat: 'precision', coefficient: 0.15 },
      ],
      element: 'physical',
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/machinist/auto_turret.png',
  },
  {
    skillId: 'machinist_assault_drone',
    classId: 'machinist',
    displayName: 'Assault Drone',
    description:
      'Launch a drone that follows and attacks your current target.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 35,
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.3,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.38,
      scaling: [
        { stat: 'techPower', coefficient: 0.38 },
        { stat: 'precision', coefficient: 0.12 },
      ],
      element: 'physical',
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/machinist/assault_drone.png',
  },
  {
    skillId: 'machinist_pulse_mine',
    classId: 'machinist',
    displayName: 'Pulse Mine',
    description:
      'Place a proximity mine that explodes when enemies approach, dealing area damage.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 15,
    coefficients: {
      basePower: 2.20,
      scaling: [
        { stat: 'techPower', coefficient: 2.20 },
        { stat: 'tech', coefficient: 0.80 },
      ],
      element: 'lightning',
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/machinist/pulse_mine.png',
  },
  {
    skillId: 'machinist_overclock',
    classId: 'machinist',
    displayName: 'Overclock',
    description:
      'Boost all deployed devices, increasing their attack speed by 35% and damage by 20% for 8 seconds.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'overclock',
      effectDuration: 8,
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/machinist/overclock.png',
  },
  {
    skillId: 'machinist_repair_protocol',
    classId: 'machinist',
    displayName: 'Repair Protocol',
    description:
      'Activate repair nanites that heal yourself or an ally over time.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 15,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 20,
    coefficients: {
      basePower: 0.60,
      scaling: [
        { stat: 'techPower', coefficient: 0.60 },
        { stat: 'tech', coefficient: 0.30 },
      ],
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/machinist/repair_protocol.png',
  },
  {
    skillId: 'machinist_shock_net',
    classId: 'machinist',
    displayName: 'Shock Net',
    description:
      'Launch an electrified net that snares enemies, slowing them and dealing periodic damage.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 25,
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 0.80,
      scaling: [{ stat: 'techPower', coefficient: 0.80 }],
      element: 'lightning',
      appliesStatus: 'snare',
      effectDuration: 4,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/machinist/shock_net.png',
  },
  {
    skillId: 'machinist_salvage',
    classId: 'machinist',
    displayName: 'Salvage',
    description:
      'Passive: Destroying your own devices or enemy devices restores Charge and has a chance to drop components.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/machinist/salvage.png',
  },
  {
    skillId: 'machinist_remote_detonation',
    classId: 'machinist',
    displayName: 'Remote Detonation',
    description:
      'Detonate a deployed device for massive area damage. Turret: 1.10, Drone: 1.40, Mine: 2.40 DevicePower.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 2.40,
      scaling: [{ stat: 'techPower', coefficient: 2.40 }],
      element: 'fire',
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/machinist/remote_detonation.png',
  },
];

// =============================================================================
// Warden Skills (Spell Power / Healing Power scaling)
// =============================================================================
const WARDEN_SKILLS: SkillDefinition[] = [
  {
    skillId: 'warden_radiant_strike',
    classId: 'warden',
    displayName: 'Radiant Strike',
    description:
      'Strike with divine light, dealing damage and generating Radiance.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'spellPower', coefficient: 1.30 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'radiant',
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/warden/radiant_strike.png',
  },
  {
    skillId: 'warden_mend',
    classId: 'warden',
    displayName: 'Mend',
    description: 'Channel healing light to restore health to an ally, generating Judgement.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 3,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'spellPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/warden/mend.png',
  },
  {
    skillId: 'warden_sanctuary',
    classId: 'warden',
    displayName: 'Sanctuary',
    description:
      'Create a field of healing light that restores health to allies within over time.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 30,
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 1,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'spellPower', coefficient: 2.40 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      appliesStatus: 'sanctuary',
      effectDuration: 8,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/warden/sanctuary.png',
  },
  {
    skillId: 'warden_condemn',
    classId: 'warden',
    displayName: 'Condemn',
    description:
      'Pass divine judgment on an enemy, dealing radiant damage and consuming Judgement.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 25,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'spellPower', coefficient: 1.90 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'radiant',
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/warden/condemn.png',
  },
  {
    skillId: 'warden_guardian_light',
    classId: 'warden',
    displayName: 'Guardian Light',
    description:
      'Shield an ally with protective light, absorbing damage based on max HP and healing power.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 25,
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.10,
      scaling: [
        { stat: 'maxHp', coefficient: 0.10 },
        { stat: 'spellPower', coefficient: 0.70 },
      ],
      appliesStatus: 'guardian_light',
      effectDuration: 6,
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/warden/guardian_light.png',
  },
  {
    skillId: 'warden_equilibrium',
    classId: 'warden',
    displayName: 'Equilibrium',
    description:
      'Balance Radiance and Judgement, consuming both to empower your next ability significantly.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 50,
    cooldownSeconds: 45,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'equilibrium',
      effectDuration: 10,
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/warden/equilibrium.png',
  },
  {
    skillId: 'warden_divine_intervention',
    classId: 'warden',
    displayName: 'Divine Intervention',
    description:
      'Call upon divine power to prevent an ally from dying, restoring them to a portion of their max health.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 40,
    cooldownSeconds: 120,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 0.30,
      scaling: [{ stat: 'maxHp', coefficient: 0.30 }],
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/warden/divine_intervention.png',
  },
  {
    skillId: 'warden_balance_within',
    classId: 'warden',
    displayName: 'Balance Within',
    description:
      'Passive: Maintaining balanced Radiance and Judgement increases your healing and damage output.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.10,
      scaling: [],
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/warden/balance_within.png',
  },
];

// =============================================================================
// Shade Skills (Physical Power scaling)
// =============================================================================
const SHADE_SKILLS: SkillDefinition[] = [
  {
    skillId: 'shade_razor_cut',
    classId: 'shade',
    displayName: 'Razor Cut',
    description:
      'A swift strike that generates Momentum. Can be chained rapidly.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'attackPower', coefficient: 1.20 },
        { stat: 'finesse', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    unlockLevel: 1,
    iconPath: 'icons/skills/shade/razor_cut.png',
  },
  {
    skillId: 'shade_shadowstep',
    classId: 'shade',
    displayName: 'Shadowstep',
    description: 'Teleport behind your target, appearing from the shadows.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 20,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 4,
    iconPath: 'icons/skills/shade/shadowstep.png',
  },
  {
    skillId: 'shade_venom_edge',
    classId: 'shade',
    displayName: 'Venom Edge',
    description:
      'Apply venom to your weapon. The 5th stack triggers a devastating poison burst.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.80,
      scaling: [
        { stat: 'attackPower', coefficient: 1.80 },
        { stat: 'luck', coefficient: 0.80 },
      ],
      element: 'nature',
      appliesStatus: 'venom',
      effectDuration: 12,
    },
    unlockLevel: 8,
    iconPath: 'icons/skills/shade/venom_edge.png',
  },
  {
    skillId: 'shade_smoke_veil',
    classId: 'shade',
    displayName: 'Smoke Veil',
    description:
      'Vanish in a cloud of smoke, becoming invisible and untargetable briefly.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'stealth',
      effectDuration: 4,
    },
    unlockLevel: 12,
    iconPath: 'icons/skills/shade/smoke_veil.png',
  },
  {
    skillId: 'shade_sever',
    classId: 'shade',
    displayName: 'Sever',
    description:
      'Spend all Momentum to deliver a devastating strike. Damage scales with Momentum consumed: 1.50/2.00/2.60/3.30/4.20 P.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'finesse', coefficient: 0.40 },
      ],
      element: 'physical',
    },
    unlockLevel: 16,
    iconPath: 'icons/skills/shade/sever.png',
  },
  {
    skillId: 'shade_execution',
    classId: 'shade',
    displayName: 'Execution',
    description:
      'Execute a target below 25% health for massive damage. Instantly kills most non-boss enemies.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 3,
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 5.00,
      scaling: [
        { stat: 'attackPower', coefficient: 5.00 },
        { stat: 'finesse', coefficient: 1.50 },
      ],
      element: 'shadow',
    },
    unlockLevel: 22,
    iconPath: 'icons/skills/shade/execution.png',
  },
  {
    skillId: 'shade_phantom_double',
    classId: 'shade',
    displayName: 'Phantom Double',
    description:
      'Create a shadowy duplicate that mimics your attacks for a short duration.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    cooldownSeconds: 24,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0.50,
      scaling: [{ stat: 'attackPower', coefficient: 0.50 }],
      element: 'shadow',
      appliesStatus: 'phantom_double',
      effectDuration: 8,
    },
    unlockLevel: 30,
    iconPath: 'icons/skills/shade/phantom_double.png',
  },
  {
    skillId: 'shade_relentless',
    classId: 'shade',
    displayName: 'Relentless',
    description:
      'Passive: Critical hits grant additional Momentum and reduce ability cooldowns.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    unlockLevel: 40,
    iconPath: 'icons/skills/shade/relentless.png',
  },
];

export const SKILLS_V1: SkillDefinition[] = [
  ...VANGUARD_SKILLS,
  ...RANGER_SKILLS,
  ...ARCANIST_SKILLS,
  ...MACHINIST_SKILLS,
  ...WARDEN_SKILLS,
  ...SHADE_SKILLS,
];
