/**
 * Skill Seed Data - MMO-5
 *
 * 48 skills (6 classes × 8 skills each).
 * All coefficients as decimals: 150% → 1.50, 15% → 0.15
 *
 * CRITICAL REQUIREMENTS:
 * - Thermal Shock: kind='reaction', internalCooldownSeconds=1 (per target)
 * - Execution: missing-HP scaling with boss cap 3.25 P
 * - Sever: per-stack coefficients 1.50/2.00/2.60/3.30/4.20
 * - Divine Intervention: anti-death + 2.50 P heal
 * - Hunter's Mark: duration 8s
 * - Remote Detonation: separate turret/drone/mine coeffs
 * - Resource costs: use resourceEffects with isPercentOfMax where spec uses %
 * - All skills have timing (castMs/activeMs/recoveryMs)
 * - Stagger coefficients where applicable
 * - PvP multipliers where applicable
 */

import { SkillDefinition } from '../models';

// =============================================================================
// Vanguard Skills (Physical Power scaling)
// Resource: Resolve (flat generation/consumption)
// =============================================================================
const VANGUARD_SKILLS: SkillDefinition[] = [
  {
    skillId: 'vanguard_cleaving_strike',
    classId: 'vanguard',
    displayName: 'Cleaving Strike',
    description:
      'A wide sweeping attack that cleaves through enemies, generating Resolve for each target hit (+8 per target).',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'resolve', amount: 8, isPercentOfMax: false, perTargetBonus: 8 },
    ],
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'strength', coefficient: 0.60 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 400, recoveryMs: 200 },
    stagger: { staggerPower: 15, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85 },
    unlockLevel: 1,
    iconPath: 'icons/skills/vanguard/cleaving_strike.png',
  },
  {
    skillId: 'vanguard_shield_breaker',
    classId: 'vanguard',
    displayName: 'Shield Breaker',
    description:
      'A devastating blow that sunders enemy defenses, applying 25% armor break for 6s.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'attackPower', coefficient: 1.90 },
        { stat: 'strength', coefficient: 1.20 },
      ],
      element: 'physical',
      appliesStatus: 'armor_break',
      effectDuration: 6,
    },
    timing: { castMs: 0, activeMs: 500, recoveryMs: 300 },
    stagger: { staggerPower: 25, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80, durationMultiplier: 0.75 },
    unlockLevel: 4,
    iconPath: 'icons/skills/vanguard/shield_breaker.png',
  },
  {
    skillId: 'vanguard_brace',
    classId: 'vanguard',
    displayName: 'Brace',
    description:
      'Channel to reduce incoming damage by 60% while braced, but movement is reduced by 30%. Cooldown starts after release.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.60,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 100 },
    stagger: { staggerPower: 0, staggerResist: 0.50, canStagger: false },
    unlockLevel: 8,
    iconPath: 'icons/skills/vanguard/brace.png',
  },
  {
    skillId: 'vanguard_counterblow',
    classId: 'vanguard',
    displayName: 'Counterblow',
    description:
      'Counter an incoming attack. Perfect timing increases damage from 2.40 P to 3.20 P.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'resolve', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'attackPower', coefficient: 2.40 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
      conditionals: [
        {
          condition: 'perfect_timing',
          basePower: 3.20,
          scaling: [
            { stat: 'attackPower', coefficient: 3.20 },
            { stat: 'strength', coefficient: 1.40 },
          ],
        },
      ],
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 400 },
    stagger: { staggerPower: 30, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.75 },
    unlockLevel: 12,
    iconPath: 'icons/skills/vanguard/counterblow.png',
  },
  {
    skillId: 'vanguard_war_cry',
    classId: 'vanguard',
    displayName: 'War Cry',
    description:
      'Let out a fearsome war cry that taunts all enemies within 8 meters for 6 seconds.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'taunt',
      effectDuration: 6,
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 200 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { durationMultiplier: 0.50 },
    unlockLevel: 16,
    iconPath: 'icons/skills/vanguard/war_cry.png',
  },
  {
    skillId: 'vanguard_earthshatter',
    classId: 'vanguard',
    displayName: 'Earthshatter',
    description:
      'Slam the ground with tremendous force, dealing damage and staggering enemies.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 35,
    resourceEffects: [
      { resourceId: 'resolve', amount: -35, isPercentOfMax: false },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'strength', coefficient: 1.00 },
      ],
      element: 'physical',
      appliesStatus: 'stagger',
      effectDuration: 2,
    },
    timing: { castMs: 200, activeMs: 400, recoveryMs: 400 },
    stagger: { staggerPower: 50, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.70, durationMultiplier: 0.50 },
    unlockLevel: 22,
    iconPath: 'icons/skills/vanguard/earthshatter.png',
  },
  {
    skillId: 'vanguard_unbreakable',
    classId: 'vanguard',
    displayName: 'Unbreakable',
    description:
      'Passive: Below 30% HP, gain 15% damage reduction and 40% stagger resistance for 8s. Internal cooldown: 30s.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 30,
    internalCooldownSeconds: 30,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.15,
      scaling: [],
      conditionals: [
        {
          condition: 'below_hp_threshold',
          threshold: 0.30,
          damageMultiplier: 0.85,
        },
      ],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, staggerResist: 0.40, canStagger: false },
    unlockLevel: 30,
    iconPath: 'icons/skills/vanguard/unbreakable.png',
  },
  {
    skillId: 'vanguard_overrun',
    classId: 'vanguard',
    displayName: 'Overrun',
    description: 'Charge forward, knocking aside enemies in your path.',
    kind: 'active',
    resourceId: 'resolve',
    resourceCost: 15,
    resourceEffects: [
      { resourceId: 'resolve', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 12,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'attackPower', coefficient: 1.30 },
        { stat: 'strength', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 600, recoveryMs: 200 },
    stagger: { staggerPower: 35, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80 },
    unlockLevel: 40,
    iconPath: 'icons/skills/vanguard/overrun.png',
  },
];

// =============================================================================
// Ranger Skills (Physical Power scaling)
// Resource: Focus (flat generation/consumption)
// =============================================================================
const RANGER_SKILLS: SkillDefinition[] = [
  {
    skillId: 'ranger_quickshot',
    classId: 'ranger',
    displayName: 'Quickshot',
    description:
      'Fire a quick shot while moving. Has 2 charges that recharge independently.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 5,
    charges: 2,
    chargeRechargeSeconds: 5,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 1.10,
      scaling: [
        { stat: 'attackPower', coefficient: 1.10 },
        { stat: 'precision', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 100 },
    stagger: { staggerPower: 5, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.90 },
    unlockLevel: 1,
    iconPath: 'icons/skills/ranger/quickshot.png',
  },
  {
    skillId: 'ranger_hunters_mark',
    classId: 'ranger',
    displayName: "Hunter's Mark",
    description:
      'Mark a target for 8s, increasing damage taken and enabling Mark-empowered abilities.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'mark',
      effectDuration: 8,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { durationMultiplier: 0.75 },
    unlockLevel: 4,
    iconPath: 'icons/skills/ranger/hunters_mark.png',
  },
  {
    skillId: 'ranger_piercing_shot',
    classId: 'ranger',
    displayName: 'Piercing Shot',
    description:
      'Fire a powerful shot that pierces through enemies. Marked targets: 3.00 P + 1.40 PRE.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 40,
    resourceEffects: [
      { resourceId: 'focus', amount: -40, isPercentOfMax: false },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 2.10,
      scaling: [
        { stat: 'attackPower', coefficient: 2.10 },
        { stat: 'precision', coefficient: 1.00 },
      ],
      element: 'physical',
      conditionals: [
        {
          condition: 'marked',
          basePower: 3.00,
          scaling: [
            { stat: 'attackPower', coefficient: 3.00 },
            { stat: 'precision', coefficient: 1.40 },
          ],
        },
      ],
    },
    timing: { castMs: 800, activeMs: 100, recoveryMs: 300 },
    stagger: { staggerPower: 20, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.75 },
    unlockLevel: 8,
    iconPath: 'icons/skills/ranger/piercing_shot.png',
  },
  {
    skillId: 'ranger_scattershot',
    classId: 'ranger',
    displayName: 'Scattershot',
    description:
      'Fire a spread of projectiles that hit multiple targets in a cone.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'focus', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 7,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 15,
    coefficients: {
      basePower: 2.70,
      scaling: [
        { stat: 'attackPower', coefficient: 2.70 },
        { stat: 'finesse', coefficient: 0.90 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 300 },
    stagger: { staggerPower: 10, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80 },
    unlockLevel: 12,
    iconPath: 'icons/skills/ranger/scattershot.png',
  },
  {
    skillId: 'ranger_evade',
    classId: 'ranger',
    displayName: 'Evade',
    description: 'Quickly dodge in the direction of movement, avoiding attacks.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 8,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 16,
    iconPath: 'icons/skills/ranger/evade.png',
  },
  {
    skillId: 'ranger_pinning_arrow',
    classId: 'ranger',
    displayName: 'Pinning Arrow',
    description: 'Fire an arrow that pins the target in place, immobilizing them.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'focus', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'attackPower', coefficient: 1.40 },
        { stat: 'precision', coefficient: 0.70 },
      ],
      element: 'physical',
      appliesStatus: 'immobilize',
      effectDuration: 3,
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 200 },
    stagger: { staggerPower: 15, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85, durationMultiplier: 0.50 },
    unlockLevel: 22,
    iconPath: 'icons/skills/ranger/pinning_arrow.png',
  },
  {
    skillId: 'ranger_dead_focus',
    classId: 'ranger',
    displayName: 'Dead Focus',
    description:
      'Enter a focused stance that drains Focus but greatly increases damage and accuracy. Cooldown starts after exit.',
    kind: 'active',
    resourceId: 'focus',
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'focus', amount: -0.05, isPercentOfMax: true },
    ],
    cooldownSeconds: 4,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'dead_focus',
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { damageMultiplier: 0.80 },
    unlockLevel: 30,
    iconPath: 'icons/skills/ranger/dead_focus.png',
  },
  {
    skillId: 'ranger_predators_instinct',
    classId: 'ranger',
    displayName: "Predator's Instinct",
    description:
      'Passive: Increases critical hit chance against Marked targets and reveals stealthed enemies.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      conditionals: [
        {
          condition: 'marked',
          damageMultiplier: 1.15,
        },
      ],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 40,
    iconPath: 'icons/skills/ranger/predators_instinct.png',
  },
];

// =============================================================================
// Arcanist Skills (Spell Power scaling)
// Resource: Mana (% of max for costs)
// NOTE: Thermal Shock is kind='reaction' with internalCooldownSeconds=1
// =============================================================================
const ARCANIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'arcanist_ember_lance',
    classId: 'arcanist',
    displayName: 'Ember Lance',
    description:
      'Launch a searing lance of flame that burns the target, applying Flame status.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 10,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.10, isPercentOfMax: true },
    ],
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'spellPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      element: 'fire',
      appliesStatus: 'flame',
      effectDuration: 6,
    },
    timing: { castMs: 500, activeMs: 100, recoveryMs: 200 },
    stagger: { staggerPower: 10, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85 },
    unlockLevel: 1,
    iconPath: 'icons/skills/arcanist/ember_lance.png',
  },
  {
    skillId: 'arcanist_frostbind',
    classId: 'arcanist',
    displayName: 'Frostbind',
    description:
      'Conjure icy chains that damage and slow the target, applying Frost status.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 12,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.12, isPercentOfMax: true },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'spellPower', coefficient: 1.20 },
        { stat: 'intellect', coefficient: 0.60 },
      ],
      element: 'ice',
      appliesStatus: 'frost',
      effectDuration: 4,
    },
    timing: { castMs: 500, activeMs: 100, recoveryMs: 200 },
    stagger: { staggerPower: 15, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85, durationMultiplier: 0.75 },
    unlockLevel: 4,
    iconPath: 'icons/skills/arcanist/frostbind.png',
  },
  {
    skillId: 'arcanist_arc_surge',
    classId: 'arcanist',
    displayName: 'Arc Surge',
    description:
      'Release a surge of lightning that chains to up to 4 nearby enemies.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 18,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.18, isPercentOfMax: true },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 1.40,
      scaling: [
        { stat: 'spellPower', coefficient: 1.40 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'lightning',
      appliesStatus: 'shock',
      effectDuration: 3,
    },
    timing: { castMs: 800, activeMs: 200, recoveryMs: 300 },
    stagger: { staggerPower: 20, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80 },
    unlockLevel: 8,
    iconPath: 'icons/skills/arcanist/arc_surge.png',
  },
  {
    skillId: 'arcanist_aether_bolt',
    classId: 'arcanist',
    displayName: 'Aether Bolt',
    description: 'Fire a bolt of pure arcane energy with a short cooldown.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 6,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.06, isPercentOfMax: true },
    ],
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.3,
    castableWhileMoving: false,
    range: 35,
    coefficients: {
      basePower: 1.60,
      scaling: [
        { stat: 'spellPower', coefficient: 1.60 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'arcane',
    },
    timing: { castMs: 300, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 5, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.90 },
    unlockLevel: 12,
    iconPath: 'icons/skills/arcanist/aether_bolt.png',
  },
  {
    skillId: 'arcanist_thermal_shock',
    classId: 'arcanist',
    displayName: 'Thermal Shock',
    description:
      'REACTION: Consumes both Flame and Frost on a target to trigger a devastating thermal reaction. 1s internal cooldown per target.',
    kind: 'reaction',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    internalCooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 2.30,
      scaling: [
        { stat: 'spellPower', coefficient: 2.30 },
        { stat: 'intellect', coefficient: 1.00 },
      ],
      element: 'arcane',
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 30, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.70 },
    unlockLevel: 16,
    iconPath: 'icons/skills/arcanist/thermal_shock.png',
  },
  {
    skillId: 'arcanist_phase_step',
    classId: 'arcanist',
    displayName: 'Phase Step',
    description: 'Teleport a short distance in the target direction.',
    kind: 'active',
    resourceId: 'mana',
    resourceCost: 15,
    resourceEffects: [
      { resourceId: 'mana', amount: -0.15, isPercentOfMax: true },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 15,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 22,
    iconPath: 'icons/skills/arcanist/phase_step.png',
  },
  {
    skillId: 'arcanist_mana_conduit',
    classId: 'arcanist',
    displayName: 'Mana Conduit',
    description:
      'Channel to rapidly restore mana. Cannot move or use other abilities while channeling.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'mana', amount: 0.08, isPercentOfMax: true },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 3,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 3000, recoveryMs: 200 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 30,
    iconPath: 'icons/skills/arcanist/mana_conduit.png',
  },
  {
    skillId: 'arcanist_elemental_mastery',
    classId: 'arcanist',
    displayName: 'Elemental Mastery',
    description:
      'Passive: Increases all elemental damage dealt by 15% and reduces elemental damage taken by 10%.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.15,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 40,
    iconPath: 'icons/skills/arcanist/elemental_mastery.png',
  },
];

// =============================================================================
// Machinist Skills (Tech/Device Power scaling)
// Resource: Charge (flat generation/consumption)
// =============================================================================
const MACHINIST_SKILLS: SkillDefinition[] = [
  {
    skillId: 'machinist_auto_turret',
    classId: 'machinist',
    displayName: 'Auto-Turret',
    description:
      'Deploy an autonomous turret that attacks nearby enemies with sustained fire.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 30,
    resourceEffects: [
      { resourceId: 'charge', amount: -30, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 0.45,
      scaling: [
        { stat: 'devicePower', coefficient: 0.45 },
        { stat: 'precision', coefficient: 0.15 },
      ],
      element: 'physical',
    },
    timing: { castMs: 500, activeMs: 200, recoveryMs: 200 },
    stagger: { staggerPower: 5, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.75 },
    unlockLevel: 1,
    iconPath: 'icons/skills/machinist/auto_turret.png',
  },
  {
    skillId: 'machinist_assault_drone',
    classId: 'machinist',
    displayName: 'Assault Drone',
    description:
      'Launch a drone that follows and attacks your current target.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 35,
    resourceEffects: [
      { resourceId: 'charge', amount: -35, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.3,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.38,
      scaling: [
        { stat: 'devicePower', coefficient: 0.38 },
        { stat: 'precision', coefficient: 0.12 },
      ],
      element: 'physical',
    },
    timing: { castMs: 300, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 3, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.70 },
    unlockLevel: 4,
    iconPath: 'icons/skills/machinist/assault_drone.png',
  },
  {
    skillId: 'machinist_pulse_mine',
    classId: 'machinist',
    displayName: 'Pulse Mine',
    description:
      'Place a proximity mine that explodes when enemies approach, dealing area damage.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'charge', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 15,
    coefficients: {
      basePower: 2.20,
      scaling: [
        { stat: 'techPower', coefficient: 2.20 },
        { stat: 'tech', coefficient: 0.80 },
      ],
      element: 'lightning',
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 200 },
    stagger: { staggerPower: 25, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.75 },
    unlockLevel: 8,
    iconPath: 'icons/skills/machinist/pulse_mine.png',
  },
  {
    skillId: 'machinist_overclock',
    classId: 'machinist',
    displayName: 'Overclock',
    description:
      'Boost all deployed devices, increasing their attack speed by 35% and damage by 20% for 8 seconds.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 20,
    resourceEffects: [
      { resourceId: 'charge', amount: -20, isPercentOfMax: false },
    ],
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'overclock',
      effectDuration: 8,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { durationMultiplier: 0.75 },
    unlockLevel: 12,
    iconPath: 'icons/skills/machinist/overclock.png',
  },
  {
    skillId: 'machinist_repair_protocol',
    classId: 'machinist',
    displayName: 'Repair Protocol',
    description:
      'Activate repair nanites that heal yourself or an ally over time.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 15,
    resourceEffects: [
      { resourceId: 'charge', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 20,
    coefficients: {
      basePower: 0.60,
      scaling: [
        { stat: 'healingPower', coefficient: 0.60 },
        { stat: 'tech', coefficient: 0.30 },
      ],
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { healingMultiplier: 0.70 },
    unlockLevel: 16,
    iconPath: 'icons/skills/machinist/repair_protocol.png',
  },
  {
    skillId: 'machinist_shock_net',
    classId: 'machinist',
    displayName: 'Shock Net',
    description:
      'Launch an electrified net that snares enemies, slowing them and dealing periodic damage.',
    kind: 'active',
    resourceId: 'charge',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'charge', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 0.80,
      scaling: [{ stat: 'techPower', coefficient: 0.80 }],
      element: 'lightning',
      appliesStatus: 'snare',
      effectDuration: 4,
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 200 },
    stagger: { staggerPower: 10, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85, durationMultiplier: 0.50 },
    unlockLevel: 22,
    iconPath: 'icons/skills/machinist/shock_net.png',
  },
  {
    skillId: 'machinist_salvage',
    classId: 'machinist',
    displayName: 'Salvage',
    description:
      'Passive: Destroying your own devices or enemy devices restores Charge and has a chance to drop components.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'charge', amount: 10, isPercentOfMax: false },
    ],
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 30,
    iconPath: 'icons/skills/machinist/salvage.png',
  },
  {
    skillId: 'machinist_remote_detonation',
    classId: 'machinist',
    displayName: 'Remote Detonation',
    description:
      'Detonate a deployed device for massive area damage. Turret: 1.10, Drone: 1.40, Mine: 2.40 DevicePower.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 1.10,
      scaling: [{ stat: 'devicePower', coefficient: 1.10 }],
      element: 'fire',
      targetVariants: {
        turret: {
          basePower: 1.10,
          scaling: [{ stat: 'devicePower', coefficient: 1.10 }],
        },
        drone: {
          basePower: 1.40,
          scaling: [{ stat: 'devicePower', coefficient: 1.40 }],
        },
        mine: {
          basePower: 2.40,
          scaling: [{ stat: 'devicePower', coefficient: 2.40 }],
        },
      },
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 200 },
    stagger: { staggerPower: 40, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.70 },
    unlockLevel: 40,
    iconPath: 'icons/skills/machinist/remote_detonation.png',
  },
];

// =============================================================================
// Warden Skills (Spell Power / Healing Power scaling)
// Resources: Radiance + Judgement (flat generation/consumption)
// =============================================================================
const WARDEN_SKILLS: SkillDefinition[] = [
  {
    skillId: 'warden_radiant_strike',
    classId: 'warden',
    displayName: 'Radiant Strike',
    description:
      'Strike with divine light, dealing damage and generating +15 Radiance.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'radiance', amount: 15, isPercentOfMax: false },
    ],
    cooldownSeconds: 2,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.30,
      scaling: [
        { stat: 'spellPower', coefficient: 1.30 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
      element: 'radiant',
    },
    timing: { castMs: 0, activeMs: 350, recoveryMs: 200 },
    stagger: { staggerPower: 12, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.85 },
    unlockLevel: 1,
    iconPath: 'icons/skills/warden/radiant_strike.png',
  },
  {
    skillId: 'warden_mend',
    classId: 'warden',
    displayName: 'Mend',
    description: 'Channel healing light to restore health to an ally, generating +15 Judgement.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'judgement', amount: 15, isPercentOfMax: false },
    ],
    cooldownSeconds: 3,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.5,
    castableWhileMoving: false,
    range: 30,
    coefficients: {
      basePower: 1.70,
      scaling: [
        { stat: 'healingPower', coefficient: 1.70 },
        { stat: 'intellect', coefficient: 0.50 },
      ],
    },
    timing: { castMs: 500, activeMs: 100, recoveryMs: 200 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { healingMultiplier: 0.70 },
    unlockLevel: 4,
    iconPath: 'icons/skills/warden/mend.png',
  },
  {
    skillId: 'warden_sanctuary',
    classId: 'warden',
    displayName: 'Sanctuary',
    description:
      'Create a field of healing light that restores health to allies within over time. Costs 30 Radiance.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 30,
    resourceEffects: [
      { resourceId: 'radiance', amount: -30, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 1,
    castableWhileMoving: false,
    range: 20,
    coefficients: {
      basePower: 2.40,
      scaling: [
        { stat: 'healingPower', coefficient: 2.40 },
        { stat: 'intellect', coefficient: 0.80 },
      ],
      appliesStatus: 'sanctuary',
      effectDuration: 8,
    },
    timing: { castMs: 1000, activeMs: 200, recoveryMs: 300 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { healingMultiplier: 0.65, durationMultiplier: 0.75 },
    unlockLevel: 8,
    iconPath: 'icons/skills/warden/sanctuary.png',
  },
  {
    skillId: 'warden_condemn',
    classId: 'warden',
    displayName: 'Condemn',
    description:
      'Pass divine judgment on an enemy, dealing radiant damage. Costs 25 Judgement.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'judgement', amount: -25, isPercentOfMax: false },
    ],
    cooldownSeconds: 10,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0.8,
    castableWhileMoving: false,
    range: 25,
    coefficients: {
      basePower: 1.90,
      scaling: [
        { stat: 'spellPower', coefficient: 1.90 },
        { stat: 'intellect', coefficient: 0.70 },
      ],
      element: 'radiant',
    },
    timing: { castMs: 800, activeMs: 100, recoveryMs: 300 },
    stagger: { staggerPower: 20, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80 },
    unlockLevel: 12,
    iconPath: 'icons/skills/warden/condemn.png',
  },
  {
    skillId: 'warden_guardian_light',
    classId: 'warden',
    displayName: 'Guardian Light',
    description:
      'Shield an ally with protective light, absorbing damage based on max HP and healing power. Costs 25 Radiance + 15 Judgement.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 25,
    resourceEffects: [
      { resourceId: 'radiance', amount: -25, isPercentOfMax: false },
      { resourceId: 'judgement', amount: -15, isPercentOfMax: false },
    ],
    cooldownSeconds: 12,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 30,
    coefficients: {
      basePower: 0.10,
      scaling: [
        { stat: 'maxHp', coefficient: 0.10 },
        { stat: 'healingPower', coefficient: 0.70 },
      ],
      appliesStatus: 'guardian_light',
      effectDuration: 6,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { healingMultiplier: 0.70, durationMultiplier: 0.75 },
    unlockLevel: 16,
    iconPath: 'icons/skills/warden/guardian_light.png',
  },
  {
    skillId: 'warden_equilibrium',
    classId: 'warden',
    displayName: 'Equilibrium',
    description:
      'Balance Radiance and Judgement, consuming 50 of each to empower your next ability significantly.',
    kind: 'active',
    resourceId: 'radiance',
    resourceCost: 50,
    resourceEffects: [
      { resourceId: 'radiance', amount: -50, isPercentOfMax: false },
      { resourceId: 'judgement', amount: -50, isPercentOfMax: false },
    ],
    cooldownSeconds: 45,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'equilibrium',
      effectDuration: 10,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { durationMultiplier: 0.80 },
    unlockLevel: 22,
    iconPath: 'icons/skills/warden/equilibrium.png',
  },
  {
    skillId: 'warden_divine_intervention',
    classId: 'warden',
    displayName: 'Divine Intervention',
    description:
      'Call upon divine power to prevent an ally from dying, granting anti-death and healing 2.50 P. Costs 40 Judgement.',
    kind: 'active',
    resourceId: 'judgement',
    resourceCost: 40,
    resourceEffects: [
      { resourceId: 'judgement', amount: -40, isPercentOfMax: false },
    ],
    cooldownSeconds: 120,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 40,
    coefficients: {
      basePower: 2.50,
      scaling: [
        { stat: 'healingPower', coefficient: 2.50 },
      ],
      appliesStatus: 'divine_intervention',
      effectDuration: 3,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { healingMultiplier: 0.60, cooldownMultiplier: 1.50 },
    unlockLevel: 30,
    iconPath: 'icons/skills/warden/divine_intervention.png',
  },
  {
    skillId: 'warden_balance_within',
    classId: 'warden',
    displayName: 'Balance Within',
    description:
      'Passive: Maintaining balanced Radiance and Judgement increases your healing and damage output by 10%.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0.10,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 40,
    iconPath: 'icons/skills/warden/balance_within.png',
  },
];

// =============================================================================
// Shade Skills (Physical Power scaling)
// Resource: Momentum (1-5 stacks, flat generation/consumption)
// =============================================================================
const SHADE_SKILLS: SkillDefinition[] = [
  {
    skillId: 'shade_razor_cut',
    classId: 'shade',
    displayName: 'Razor Cut',
    description:
      'A swift strike that generates +1 Momentum. Can be chained rapidly.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'momentum', amount: 1, isPercentOfMax: false },
    ],
    cooldownSeconds: 1,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.20,
      scaling: [
        { stat: 'attackPower', coefficient: 1.20 },
        { stat: 'finesse', coefficient: 0.50 },
      ],
      element: 'physical',
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 150 },
    stagger: { staggerPower: 8, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.90 },
    unlockLevel: 1,
    iconPath: 'icons/skills/shade/razor_cut.png',
  },
  {
    skillId: 'shade_shadowstep',
    classId: 'shade',
    displayName: 'Shadowstep',
    description: 'Teleport behind your target, appearing from the shadows.',
    kind: 'active',
    resourceId: null,
    resourceCost: 0,
    cooldownSeconds: 8,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 20,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 4,
    iconPath: 'icons/skills/shade/shadowstep.png',
  },
  {
    skillId: 'shade_venom_edge',
    classId: 'shade',
    displayName: 'Venom Edge',
    description:
      'Apply venom to your weapon. The 5th stack triggers a devastating poison burst: 1.80 P + 0.80 LCK DoT. Costs 1 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    resourceEffects: [
      { resourceId: 'momentum', amount: -1, isPercentOfMax: false },
    ],
    cooldownSeconds: 14,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.80,
      scaling: [
        { stat: 'attackPower', coefficient: 1.80 },
        { stat: 'luck', coefficient: 0.80 },
      ],
      element: 'nature',
      appliesStatus: 'venom',
      effectDuration: 12,
    },
    timing: { castMs: 0, activeMs: 200, recoveryMs: 200 },
    stagger: { staggerPower: 5, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.80, durationMultiplier: 0.75 },
    unlockLevel: 8,
    iconPath: 'icons/skills/shade/venom_edge.png',
  },
  {
    skillId: 'shade_smoke_veil',
    classId: 'shade',
    displayName: 'Smoke Veil',
    description:
      'Vanish in a cloud of smoke, becoming invisible and untargetable briefly. Costs 2 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    resourceEffects: [
      { resourceId: 'momentum', amount: -2, isPercentOfMax: false },
    ],
    cooldownSeconds: 20,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
      appliesStatus: 'stealth',
      effectDuration: 4,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { durationMultiplier: 0.75 },
    unlockLevel: 12,
    iconPath: 'icons/skills/shade/smoke_veil.png',
  },
  {
    skillId: 'shade_sever',
    classId: 'shade',
    displayName: 'Sever',
    description:
      'Spend all Momentum to deliver a devastating strike. Per-stack damage: 1.50/2.00/2.60/3.30/4.20 P + 0.40 FIN/stack.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 1,
    resourceEffects: [
      { resourceId: 'momentum', amount: -5, isPercentOfMax: false },
    ],
    cooldownSeconds: 6,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'finesse', coefficient: 0.40 },
      ],
      element: 'physical',
      perStack: {
        basePowerPerStack: [1.50, 2.00, 2.60, 3.30, 4.20],
        scalingPerStack: [
          [{ stat: 'attackPower', coefficient: 1.50 }, { stat: 'finesse', coefficient: 0.40 }],
          [{ stat: 'attackPower', coefficient: 2.00 }, { stat: 'finesse', coefficient: 0.80 }],
          [{ stat: 'attackPower', coefficient: 2.60 }, { stat: 'finesse', coefficient: 1.20 }],
          [{ stat: 'attackPower', coefficient: 3.30 }, { stat: 'finesse', coefficient: 1.60 }],
          [{ stat: 'attackPower', coefficient: 4.20 }, { stat: 'finesse', coefficient: 2.00 }],
        ],
      },
    },
    timing: { castMs: 0, activeMs: 350, recoveryMs: 250 },
    stagger: { staggerPower: 25, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.70 },
    unlockLevel: 16,
    iconPath: 'icons/skills/shade/sever.png',
  },
  {
    skillId: 'shade_execution',
    classId: 'shade',
    displayName: 'Execution',
    description:
      'Execute a target below 25% health. Damage scales with missing HP. Boss cap: 3.25 P. Costs 3 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 3,
    resourceEffects: [
      { resourceId: 'momentum', amount: -3, isPercentOfMax: false },
    ],
    cooldownSeconds: 18,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 1.50,
      scaling: [
        { stat: 'attackPower', coefficient: 1.50 },
        { stat: 'missingHp', coefficient: 0.03 },
        { stat: 'finesse', coefficient: 0.50 },
      ],
      element: 'shadow',
      conditionals: [
        {
          condition: 'below_hp_threshold',
          threshold: 0.25,
          damageMultiplier: 1.50,
        },
        {
          condition: 'boss_target',
          basePower: 3.25,
          scaling: [
            { stat: 'attackPower', coefficient: 3.25 },
            { stat: 'finesse', coefficient: 1.00 },
          ],
        },
      ],
    },
    timing: { castMs: 0, activeMs: 300, recoveryMs: 300 },
    stagger: { staggerPower: 35, canStagger: true },
    pvpMultipliers: { damageMultiplier: 0.60 },
    unlockLevel: 22,
    iconPath: 'icons/skills/shade/execution.png',
  },
  {
    skillId: 'shade_phantom_double',
    classId: 'shade',
    displayName: 'Phantom Double',
    description:
      'Create a shadowy duplicate that mimics your attacks for a short duration. Costs 2 Momentum.',
    kind: 'active',
    resourceId: 'momentum',
    resourceCost: 2,
    resourceEffects: [
      { resourceId: 'momentum', amount: -2, isPercentOfMax: false },
    ],
    cooldownSeconds: 24,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: true,
    range: 0,
    coefficients: {
      basePower: 0.50,
      scaling: [{ stat: 'attackPower', coefficient: 0.50 }],
      element: 'shadow',
      appliesStatus: 'phantom_double',
      effectDuration: 8,
    },
    timing: { castMs: 0, activeMs: 100, recoveryMs: 100 },
    stagger: { staggerPower: 0, canStagger: false },
    pvpMultipliers: { damageMultiplier: 0.75, durationMultiplier: 0.75 },
    unlockLevel: 30,
    iconPath: 'icons/skills/shade/phantom_double.png',
  },
  {
    skillId: 'shade_relentless',
    classId: 'shade',
    displayName: 'Relentless',
    description:
      'Passive: Critical hits grant additional Momentum and reduce ability cooldowns by 10%.',
    kind: 'passive',
    resourceId: null,
    resourceCost: 0,
    resourceEffects: [
      { resourceId: 'momentum', amount: 1, isPercentOfMax: false },
    ],
    cooldownSeconds: 0,
    charges: 1,
    chargeRechargeSeconds: 0,
    castTimeSeconds: 0,
    castableWhileMoving: false,
    range: 0,
    coefficients: {
      basePower: 0,
      scaling: [],
    },
    timing: { castMs: 0, activeMs: 0, recoveryMs: 0 },
    stagger: { staggerPower: 0, canStagger: false },
    unlockLevel: 40,
    iconPath: 'icons/skills/shade/relentless.png',
  },
];

export const SKILLS_V1: SkillDefinition[] = [
  ...VANGUARD_SKILLS,
  ...RANGER_SKILLS,
  ...ARCANIST_SKILLS,
  ...MACHINIST_SKILLS,
  ...WARDEN_SKILLS,
  ...SHADE_SKILLS,
];
