/**
 * Status Effect Seed Data - MMO-5
 *
 * Status effects referenced by skills and combat mechanics.
 */

import { StatusDefinition } from '../models';

export const STATUSES_V1: StatusDefinition[] = [
  // Damage over time effects
  {
    statusId: 'flame',
    displayName: 'Flame',
    description: 'Burning from fire damage, taking damage over time.',
    category: 'dot',
    maxStacks: 3,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/flame.png',
  },
  {
    statusId: 'burn',
    displayName: 'Burn',
    description: 'Severely burning, taking increased fire damage over time.',
    category: 'dot',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/burn.png',
  },
  {
    statusId: 'venom',
    displayName: 'Venom',
    description: 'Poisoned, taking nature damage over time. Stacks to 5.',
    category: 'dot',
    maxStacks: 5,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/venom.png',
  },
  {
    statusId: 'poison',
    displayName: 'Poison',
    description: 'A general poison effect dealing nature damage over time.',
    category: 'dot',
    maxStacks: 3,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/poison.png',
  },

  // Control effects
  {
    statusId: 'frost',
    displayName: 'Frost',
    description: 'Chilled by ice, movement and attack speed reduced.',
    category: 'control',
    maxStacks: 3,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/frost.png',
  },
  {
    statusId: 'freeze',
    displayName: 'Freeze',
    description: 'Frozen solid, unable to move or act.',
    category: 'control',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/freeze.png',
  },
  {
    statusId: 'shock',
    displayName: 'Shock',
    description: 'Shocked by electricity, periodically interrupted.',
    category: 'control',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/shock.png',
  },
  {
    statusId: 'stagger',
    displayName: 'Stagger',
    description: 'Staggered, briefly unable to act.',
    category: 'control',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/stagger.png',
  },
  {
    statusId: 'immobilize',
    displayName: 'Immobilize',
    description: 'Rooted in place, unable to move but can still attack.',
    category: 'control',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/immobilize.png',
  },
  {
    statusId: 'snare',
    displayName: 'Snare',
    description: 'Movement speed greatly reduced.',
    category: 'control',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/snare.png',
  },
  {
    statusId: 'taunt',
    displayName: 'Taunt',
    description: 'Forced to attack the taunting enemy.',
    category: 'control',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/taunt.png',
  },

  // Debuffs
  {
    statusId: 'armor_break',
    displayName: 'Armor Break',
    description: 'Armor reduced, taking increased physical damage.',
    category: 'debuff',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/armor_break.png',
  },
  {
    statusId: 'weaken',
    displayName: 'Weaken',
    description: 'Weakened, dealing reduced damage.',
    category: 'debuff',
    maxStacks: 3,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/weaken.png',
  },
  {
    statusId: 'exhausted',
    displayName: 'Exhausted',
    description: 'Exhausted, resource regeneration greatly reduced.',
    category: 'debuff',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/exhausted.png',
  },
  {
    statusId: 'mark',
    displayName: 'Mark',
    description: "Hunter's Mark - taking increased damage from the marking enemy.",
    category: 'debuff',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/mark.png',
  },

  // Buffs
  {
    statusId: 'stealth',
    displayName: 'Stealth',
    description: 'Hidden from enemies, next attack deals bonus damage.',
    category: 'buff',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/stealth.png',
  },
  {
    statusId: 'dead_focus',
    displayName: 'Dead Focus',
    description: 'Perfectly focused, increased damage and accuracy.',
    category: 'buff',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/dead_focus.png',
  },
  {
    statusId: 'overclock',
    displayName: 'Overclock',
    description: 'Devices overclocked, increased attack speed and damage.',
    category: 'buff',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/overclock.png',
  },
  {
    statusId: 'guardian_light',
    displayName: 'Guardian Light',
    description: 'Protected by divine light, absorbing incoming damage.',
    category: 'buff',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/guardian_light.png',
  },
  {
    statusId: 'equilibrium',
    displayName: 'Equilibrium',
    description: 'In perfect balance, next ability greatly empowered.',
    category: 'buff',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/equilibrium.png',
  },
  {
    statusId: 'phantom_double',
    displayName: 'Phantom Double',
    description: 'A shadowy duplicate mimics your attacks.',
    category: 'buff',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/phantom_double.png',
  },
  {
    statusId: 'unbreakable',
    displayName: 'Unbreakable',
    description: 'Cannot be brought below 1 HP, damage reduction active.',
    category: 'buff',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/unbreakable.png',
  },

  // Healing over time
  {
    statusId: 'sanctuary',
    displayName: 'Sanctuary',
    description: 'Within a sanctuary field, healing over time.',
    category: 'hot',
    maxStacks: 1,
    dispellable: false,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/sanctuary.png',
  },
  {
    statusId: 'harmony',
    displayName: 'Harmony',
    description: 'In harmony with allies, increased healing received.',
    category: 'hot',
    maxStacks: 1,
    dispellable: true,
    persistsThroughDeath: false,
    iconPath: 'icons/statuses/harmony.png',
  },
];
